### ISSUE TITLE
Edit and create new User Story,User Role and Project Proposal 

### ISSUE THREAD

**Issue by hiral1213** [joshiaarsh/jobPortal#6]

**Comment by SunmiYoonDev** [comment]
This is our proposal documentation.
[Project Proposal Final.docx](https://github.com/joshiaarsh/jobPortal/files/2842977/Project.Proposal.Final.docx)

**Comment by SunmiYoonDev** [comment]
This is our user roles documentation.
[User Roles.docx](https://github.com/joshiaarsh/jobPortal/files/2842978/User.Roles.docx)

**Comment by SunmiYoonDev** [comment]
This is our user stories documentation.
[User Stories.docx](https://github.com/joshiaarsh/jobPortal/files/2842980/User.Stories.docx)
